spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?useMysqlMetadata=true
    username: test
    password: password

  flyway:
    baseline-on-migrate: true
